src/GlobalStyle.ts, src/GlobalThemeConfig.ts, src/components/common/NavLayout.tsx
- 기본 Layout min-width 1024px 적용
- 공통 색상 추가
`green-1` : success color
`red-1` : error color
`yellow-1`, `purple-1` : etc color
=> [Style] 공통 스타일 추가

src/GlobalStyle.ts, src/GlobalThemeConfig.ts, src/components/common/NavLayout.tsx, src/components/dayoff/DayOffHistoryItem.tsx, src/components/dayoff/DayOffRequestItem.tsx, src/components/dayoff/DayOffSummary.tsx, src/components/dayoff/MyDayOffCount.tsx, src/components/dayoff/index.ts, src/components/index.ts, src/constants/dayOffTypes.ts, src/constants/index.ts, src/pages/App.tsx, src/pages/DayOff.tsx, src/pages/index.ts
연차 페이지 UI 작업
연차 등록 버튼
나의 연차 > 연차 summary
연차 신청 내역 목록
연차 사용 내역 목록
연차 취소 메뉴 추가 
closed #1
레이아웃 높이를 수정했는데 작업하시다가 이상하면 말씀해주세요!
=> [Feat] 연차 페이지 UI 작업 반영 

src/components/signup/SignUp.tsx, src/components/signup/index.ts, src/components/signup/styled.ts, src/pages/App.tsx
- 회원가입 폼 완료
closed #11
추가해야 될 것
- 로고
- API
=> [Feat]회원가입 페이지 UI 작업

src/components/common/NavLayout.tsx, src/components/dayoff/DayOffHistoryItem.tsx, src/components/dayoff/DayOffRequestItem.tsx, src/components/duty/DutyHistoryItem.tsx, src/components/duty/DutyRequestItem.tsx, src/components/duty/index.ts, src/components/index.ts, src/constants/dummyData.ts, src/constants/index.ts, src/constants/menuItems.ts, src/constants/status.ts, src/pages/App.tsx, src/pages/DayOff.tsx, src/pages/Duty.tsx, src/pages/index.ts
- 당직 페이지 UI 작업 완료
- 당직 신청 내역 UI 작업
- 당직 신청 취소 버튼
- 당직 기록 리스트 UI 작업
- 당직 등록 버튼 추가
closed #4 
NavBar z-index 수정했습니다.
=> [Feat] 당직 페이지 UI 작업 반영

src/pages/Login.tsx, src/pages/MyPage.tsx, src/pages/SignUp.tsx, src/stores/userStore.ts
유효성검사
- 로그인페이지 내 이메일
- 회원가입페이지 내 이메일, 비밀번호, 핸드폰번호
상태관리
- stores/userStore.ts
- 로그인페이지
- 마이페이지
=> [Feat] 상태관리, 유효성 검사 추가

src/apis/authRequests.ts, src/apis/axios.ts, src/apis/index.ts, src/apis/scheduleRequests.ts, src/pages/HomeCalendar.tsx, src/types/ICalendarUser.ts, src/types/ICommonResponse.ts, src/types/index.ts
=> [Feat] axios setting

src/apis/dutyRequests.ts, src/apis/scheduleRequests.ts, src/components/dayoff/DayOffHistoryTable.tsx, src/components/dayoff/DayOffRequestTable.tsx, src/components/duty/DutyRequestTable.tsx, src/constants/menuItems.ts, src/constants/status.ts, src/types/dayoff/IDayOffResponse.ts, src/utils/filterUtils.ts
=> [Fix] Enum 값 수정

src/apis/scheduleRequests.ts, src/components/dayoff/DayOffRequestModal.tsx, src/components/dayoff/DayOffRequestTable.tsx, src/constants/resultModalDatas.ts, src/pages/App.tsx, src/pages/DayOff.tsx, src/utils/calcNumOfDayOff.ts
- 휴가 취소하기 기능 추가
- 휴가 취소 성공 시 메시지 노출
- 휴가 취소 실패 시 예외처리 추가
- 휴가 신청 시 신청가능 휴가일수 예외처리 추가
closed #40
=> [Feat] 휴가 취소 기능 반영

src/apis/dutyRequests.ts, src/apis/scheduleRequests.ts, src/components/dayoff/DayOffRequestModal.tsx, src/components/dayoff/DayOffRequestTable.tsx, src/components/duty/DutyRequestTable.tsx, src/constants/resultModalDatas.ts, src/pages/App.tsx, src/pages/DayOff.tsx, src/pages/Duty.tsx, src/utils/calcNumOfDayOff.ts
- 당직 신청 취소 API 연동
- 당직 신청 취소 성공 시 메시지 노출
- 당직 신청 취소 실패 시 예외처리 추가
closed #41
=> [Feat] 당직 신청 취소 기능 반영

src/apis/scheduleRequests.ts, src/pages/DayOff.tsx, src/types/IUserSearchResponse.ts, src/types/dayoff/IDayOffResponse.ts, src/types/index.ts
휴가일수 조회 API + 휴가내역 조회 API axios all을 통해 한번에 조회하도록 수정
closed #50
=> [Feat] 휴가일수 조회 연동

src/apis/adminScheduleRequests.ts, src/components/admin/DutyMgt.tsx, src/components/admin/ScheduleMgt.tsx, src/components/common/AppNav.tsx, src/components/common/NotificationPopup.tsx, src/components/duty/DutyRequestTable.tsx, src/stores/dayOffListStore.ts, src/types/admin/Schedule.ts
- 파이어베이스 알림에 사용자 아이디가 연동 될 수 있도록 수정
=> [Feat] 파이어베이스 알림 연동

src/components/admin/DutyMgt.tsx, src/components/admin/EmployeeMgt.tsx, src/components/admin/ScheduleMgt.tsx, src/components/dayoff/DayOffHistoryTable.tsx, src/components/dayoff/DayOffRequestTable.tsx, src/components/duty/DutyHistoryTable.tsx, src/components/duty/DutyRequestTable.tsx, src/pages/Login.tsx
1. 로그인 시 Enter키 눌러도 onSubmit 함수 동작하게 수정
2. 휴가/당직 Table 텍스트 가운데정렬 수정
3. admin 휴가/당직관리 '처리중' 리스트가 위로 오도록 정렬 수정
4. Pagination 가운데정렬 수정
=> fix: 스타일 수정

package-lock.json, package.json, src/components/calendar/CalendarHeader.tsx, src/components/calendar/ScheduleCalendar.tsx, src/constants/excel.ts, src/constants/index.ts, src/types/common/IExcelData.ts, src/types/common/index.ts, src/utils/index.ts, src/utils/parseExcelDatas.ts
엑셀 다운로드 기능 추가
closed #63 
- react-csv 라이브러리 설치했습니다.
=> [Feat] 엑셀 다운로드

src/apis/adminScheduleRequests.ts, src/components/admin/DutyMgt.tsx, src/components/admin/EmployeeMgt.tsx, src/components/admin/ScheduleMgt.tsx, src/stores/employeeListStore.ts, src/types/admin/Employee.ts, src/types/admin/EmployeeUpdate.ts
=> admin관련 파일 타입오류 수정

src/components/admin/EmployeeMgt.tsx
=> [fix] 타입에러수정

public/_redirects
=> [build]: 배포코드수정

src/components/common/AppNav.tsx, src/pages/App.tsx
=> deploy: 배포경로 admin 오류 url 변경시도

src/apis/scheduleRequests.ts, src/components/calendar/UserDropdown.tsx, src/components/common/AppNav.tsx, src/pages/MyPage.tsx, src/pages/SignUp.tsx
=> Style: 프로필 사진 변경, console삭제

src/components/calendar/UserDropdown.tsx, src/components/common/AppNav.tsx, src/pages/MyPage.tsx, src/pages/SignUp.tsx
=> deploy: 타입에러 수정

src/components/admin/DutyMgt.tsx, src/components/admin/ScheduleMgt.tsx
=> style: 승인/반려 버튼 사이 간격 조정

src/pages/SignUp.tsx
=> [Feat]회원가입 유효성검사 수정
